radsim(filebase,time,track,snr,...
       'timeseries' ,@chirppulse,'parameters',[pulseBandwidth pulseLength prf],...
       'fs',Fs,'fc',Fc,'transmitgeometry',geom,...
       'transmitorientation',orientation,'clutter',reflextivity',...
       'transmitshading',weights,'rangecorrect',true); 